# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:3000
    depends_on:
      - db
    restart: on-failure
